### ISSUE TITLE
feat: 앨범 사진 등록용 api 제작

### ISSUE THREAD

**Issue by sunyou10** [9oormthonUniv-seoultech/PROJECT_TEAM_WEB_BE11#17]
## 🚀 Description

- 앨범 등록 과정에 사용될 api 제작

## ✅ TODO

- [ ]  QR 인식용 API 제작
- [ ]  갤러리 사진 등록용 API 제작
- [ ] 사진 촬영 일자, 부스 위치, 해시태그, 기록 내용을 DB에 저장
- [ ] 링크 공유 기능

## 📍etc

> 화이팅!
