### ISSUE TITLE
feat : s3연결 및 ci/cd

### ISSUE THREAD

**Issue by sooieese00** [9oormthonUniv-seoultech/PROJECT_TEAM_WEB_BE11#2]
## 🚀 Description

- s3 연결

## ✅ TODO

- [ ]  s3 연결 코드 작성
- [ ] 테스트: 이미지 업로드
- [ ] s3 ci/cd 구축

## 📍etc

> multer, multer-s3 라이브러리 사용하게 될 것 같습니다
