### ISSUE TITLE
feat: 중간테이블 추가 및 db 수정

### ISSUE THREAD

**Issue by sunyou10** [9oormthonUniv-seoultech/PROJECT_TEAM_WEB_BE11#5]
## 🚀 Description

- MySQL 데이터베이스 테이블 추가 및 user 테이블 수정

## ✅ TODO

- [x]  즐겨찾기한 포토부스 정보를 저장할 `photobooth_like` 중간테이블 생성
- [x] `user`와 `photobooth_like` 연결
- [x] `user` 에 사용자 프로필 사진을 저장할 attribute 추가
- [x] `user` 내용 수정 및 삭제할 수 있는 api 생성

## 📍etc

> photobooth_like 관련 api는 photobooth 데이터 저장 이후에 만드는 것이 좋을 것 같아 일단 user 관련만 제작하겠습니다.
