### ISSUE TITLE
feat: DB에 포토부스 정보 저장

### ISSUE THREAD

**Issue by sunyou10** [9oormthonUniv-seoultech/PROJECT_TEAM_WEB_BE11#8]
## 🚀 Description

- Photobooth 테이블에 포토부스 정보 저장

## ✅ TODO

- [x] 포토부스 데이터 크롤링
- [x] 주소를 위경도로 변환
- [x] Photobooth 테이블에 내용 저장

## 📍etc

>
